{
   "type":"record",
   "name":"store_sales_denorm_hudi_record",
   "namespace":"hoodie.store_sales_denorm_hudi",
   "fields":[
      {
         "name":"ss_sold_time_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"ss_item_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"ss_customer_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"ss_cdemo_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"ss_hdemo_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"ss_addr_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"ss_store_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"ss_promo_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"ss_ticket_number",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"ss_quantity",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"ss_wholesale_cost",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.ss_wholesale_cost",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"ss_list_price",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.ss_list_price",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"ss_sales_price",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.ss_sales_price",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"ss_ext_discount_amt",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.ss_ext_discount_amt",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"ss_ext_sales_price",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.ss_ext_sales_price",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"ss_ext_wholesale_cost",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.ss_ext_wholesale_cost",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"ss_ext_list_price",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.ss_ext_list_price",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"ss_ext_tax",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.ss_ext_tax",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"ss_coupon_amt",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.ss_coupon_amt",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"ss_net_paid",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.ss_net_paid",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"ss_net_paid_inc_tax",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.ss_net_paid_inc_tax",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"ss_net_profit",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.ss_net_profit",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"d_date_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_date_id",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"d_date",
         "type":[
            {
               "type":"int",
               "logicalType":"date"
            },
            "null"
         ]
      },
      {
         "name":"d_month_seq",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_week_seq",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_quarter_seq",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_year",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_dow",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_moy",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_dom",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_qoy",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_fy_year",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_fy_quarter_seq",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_fy_week_seq",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_day_name",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"d_quarter_name",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"d_holiday",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"d_weekend",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"d_following_holiday",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"d_first_dom",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_last_dom",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_same_day_ly",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_same_day_lq",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"d_current_day",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"d_current_week",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"d_current_month",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"d_current_quarter",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"d_current_year",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"t_time_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"t_time_id",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"t_time",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"t_hour",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"t_minute",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"t_second",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"t_am_pm",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"t_shift",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"t_sub_shift",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"t_meal_time",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"c_customer_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"c_customer_id",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"c_current_cdemo_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"c_current_hdemo_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"c_current_addr_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"c_first_shipto_date_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"c_first_sales_date_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"c_salutation",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"c_first_name",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"c_last_name",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"c_preferred_cust_flag",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"c_birth_day",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"c_birth_month",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"c_birth_year",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"c_birth_country",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"c_login",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"c_email_address",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"c_last_review_date",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"cd_demo_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"cd_gender",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"cd_marital_status",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"cd_education_status",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"cd_purchase_estimate",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"cd_credit_rating",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"cd_dep_count",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"cd_dep_employed_count",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"cd_dep_college_count",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"hd_demo_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"hd_income_band_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"hd_buy_potential",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"hd_dep_count",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"hd_vehicle_count",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"ca_address_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"ca_address_id",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"ca_street_number",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"ca_street_name",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"ca_street_type",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"ca_suite_number",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"ca_city",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"ca_county",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"ca_state",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"ca_zip",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"ca_country",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"ca_gmt_offset",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.ca_gmt_offset",
               "size":3,
               "logicalType":"decimal",
               "precision":5,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"ca_location_type",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_store_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"s_store_id",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_rec_start_date",
         "type":[
            {
               "type":"int",
               "logicalType":"date"
            },
            "null"
         ]
      },
      {
         "name":"s_rec_end_date",
         "type":[
            {
               "type":"int",
               "logicalType":"date"
            },
            "null"
         ]
      },
      {
         "name":"s_closed_date_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"s_store_name",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_number_employees",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"s_floor_space",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"s_hours",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_manager",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_market_id",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"s_geography_class",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_market_desc",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_market_manager",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_division_id",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"s_division_name",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_company_id",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"s_company_name",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_street_number",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_street_name",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_street_type",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_suite_number",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_city",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_county",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_state",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_zip",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_country",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"s_gmt_offset",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.s_gmt_offset",
               "size":3,
               "logicalType":"decimal",
               "precision":5,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"s_tax_precentage",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.s_tax_precentage",
               "size":3,
               "logicalType":"decimal",
               "precision":5,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"p_promo_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"p_promo_id",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"p_start_date_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"p_end_date_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"p_item_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"p_cost",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.p_cost",
               "size":7,
               "logicalType":"decimal",
               "precision":15,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"p_response_target",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"p_promo_name",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"p_channel_dmail",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"p_channel_email",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"p_channel_catalog",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"p_channel_tv",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"p_channel_radio",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"p_channel_press",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"p_channel_event",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"p_channel_demo",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"p_channel_details",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"p_purpose",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"p_discount_active",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"i_item_sk",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"i_item_id",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"i_rec_start_date",
         "type":[
            {
               "type":"int",
               "logicalType":"date"
            },
            "null"
         ]
      },
      {
         "name":"i_rec_end_date",
         "type":[
            {
               "type":"int",
               "logicalType":"date"
            },
            "null"
         ]
      },
      {
         "name":"i_item_desc",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"i_current_price",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.i_current_price",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"i_wholesale_cost",
         "type":[
            {
               "type":"fixed",
               "name":"fixed",
               "namespace":"hoodie.store_sales_denorm_hudi.store_sales_denorm_hudi_record.i_wholesale_cost",
               "size":4,
               "logicalType":"decimal",
               "precision":7,
               "scale":2
            },
            "null"
         ]
      },
      {
         "name":"i_brand_id",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"i_brand",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"i_class_id",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"i_class",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"i_category_id",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"i_category",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"i_manufact_id",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"i_manufact",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"i_size",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"i_formulation",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"i_color",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"i_units",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"i_container",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"i_manager_id",
         "type":[
            "int",
            "null"
         ]
      },
      {
         "name":"i_product_name",
         "type":[
            "string",
            "null"
         ]
      },
      {
         "name":"ss_sold_date_sk",
         "type":[
            "int",
            "null"
         ]
      }
   ]
}