version: '2.0'
services:
    namenodeservice:
        image: prestohiveservermult:dev
        container_name: namenodecontainer
        ports:
            - 10000:10000
        volumes:
            #Only used for reading .dat files for database creation (use parent folder).
            - ./../hivevol:/temporal
            - ./warehousevol:/user/hive/warehouse
            - ./metastorevol:/metastore
    slave1service:
        image: prestoslave1mult:dev
        container_name: slave1container
    slave2service:
        image: prestoslave2mult:dev
        container_name: slave2container
    postgresservice:
        image: postgres:10.6
        container_name: postgrescontainer
        volumes:
            - postgresdbmultinodevol:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: metastore
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres
    hiveclient:
        image: clientbuilder:dev
        container_name: clientbuildercontainer
        volumes:
            - ./../client/project:/project
            - ./datavol:/data
        entrypoint:
            - bash
        tty: true
        stdin_open: true
volumes:
    postgresdbmultinodevol:


