version: '2.0'
services:
    namenodeservice:
        image: sparkmaster:dev
        container_name: namenodecontainer
        ports:
            - 10000:10000
            - 4040:4040
            - 6066:6066
            - 7077:7077
            - 8080:8080
        volumes:
            #- ./hivevol:/temporal
            - ./warehousevol:/user/hive/warehouse
            - ./metastorevol:/metastore
            - ./datavol:/data
            - ./client/project/target:/project
    slave1service:
        image: sparkslave:dev
        container_name: slave1container
    slave2service:
        image: sparkslave:dev
        container_name: slave2container
    postgresservice:
        image: postgres:10.6
        container_name: postgrescontainer
        volumes:
            - postgresdbmultinodevol:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: metastore
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres
#    hiveclient:
#        image: buildhiveclient:dev
#        container_name: sparkhiveclientcontainer
#        volumes:
#            - ./client/project:/project
#        entrypoint:
#            - bash
#        tty: true
#        stdin_open: true
volumes:
    postgresdbmultinodevol:


