version: '2.0'
services:
    namenodeservice:
        image: sparkmaster:dev
        container_name: namenodecontainer
        ports:
            - 10000:10000 #HiveServer2 Thrift interface
            - 4040:4040 #Running Spark driver GUI for first application
            - 4041:4041 #Running Spark driver GUI for second application
            - 6066:6066 #Master REST service
            - 7077:7077 #Spark master job submission
            - 8080:8080 #Spark standalone GUI
            - 18080:18080 #Spark history server
            - 8088:8088 #Yarn job UI
        volumes:
            - ./warehousevol:/user/hive/warehouse
            - ./metastorevol:/metastore
            #- ./datavol:/data
            #- ./client/project/targetspark:/project/targetspark
    slave1service:
        image: sparkslave:dev
        container_name: slave1container
    slave2service:
        image: sparkslave:dev
        container_name: slave2container
    postgresservice:
        image: postgres:10.6
        container_name: postgrescontainer
        volumes:
            - postgresdbmultinodevol:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: metastore
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres
    hiveclient:
        image: buildhiveclient:dev
        container_name: hiveclientcontainer
        volumes:
            - ./client/project:/project
            - ./datavol:/data
        entrypoint:
            - bash
        tty: true
        stdin_open: true
volumes:
    postgresdbmultinodevol:


