version: '2.0'
services:
    hiveservice:
        image: hiveserver:dev
        container_name: hiveservercontainer
        ports:
            - 10000:10000
        volumes:
            - ./server/hivevol:/tmp
    hiveclient:
        image: buildhiveclient:dev
        container_name: hiveclientcontainer
        volumes:
            - ./client/project:/project
        entrypoint:
            - bash
        tty: true
        stdin_open: true


