version: '2.0'
services:
    sparkhiveservice:
        image: sparkhiveserver:dev
        container_name: sparkhiveservercontainer
        expose:
            - 7001
            - 7002
            - 7003
            - 7004
            - 7005
            - 7077
            - 6066
        ports:
            - 10000:10000
            - 4040:4040
            - 6066:6066
            - 7077:7077
            - 8080:8080
        volumes:
            - ./hivevol:/temporal
            - ./warehousevol:/user/hive/warehouse
            - ./metastorevol:/metastore
    sparkworkerservice:
        image: sparkworker:dev
        container_name: sparkworkercontainer
        environment:
            SPARK_WORKER_CORES: 2
            SPARK_WORKER_MEMORY: 4g
        expose:
            - 7012
            - 7013
            - 7014
            - 7015
            - 8881
        ports:
            - 8081:8081
        volumes:
            - ./hivevol:/temporal
            - ./warehousevol:/user/hive/warehouse
            - ./metastorevol:/metastore
    postgresservice:
        image: postgres:10.6
        container_name: postgrescontainer
        volumes:
            - postgresdbvol:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: metastore
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres
    sparkhiveclient:
        image: buildsparkhiveclient:dev
        container_name: sparkhiveclientcontainer
        volumes:
            - ./client/project:/project
            - ./datavol:/data
        entrypoint:
            - bash
        tty: true
        stdin_open: true
volumes:
    postgresdbvol:


