version: '2.0'
services:
    hiveservice:
        image: prestohiveserver:dev
        container_name: mastercontainer
        ports:
            - 10000:10000 #HiveServer2 Thrift interface
            - 8088:8088 #Hadoop/Yarn job UI
            - 19888:19888 #Hadoop job history
            - 8080:8080 #Presto web ui
        volumes:
            #Only used for reading .dat files for database creation.
            - ./hivevol:/temporal
            - ./warehousevol:/user/hive/warehouse
            - ./metastorevol:/metastore
        environment:
            - USER_NAME_DC=${USER_NAME_DC}
    postgresservice:
        image: postgres:10.6
        container_name: postgrescontainer
        volumes:
            - postgresdbvol:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: metastore
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres
    hiveclient:
        image: clientbuilder:dev
        container_name: clientbuildercontainer
        volumes:
            - ./client/project:/project
            - ./datavol:/data
        entrypoint:
            - bash
        tty: true
        stdin_open: true
volumes:
    postgresdbvol:


