version: '2.0'
services:
    hiveservice:
        image: prestohiveserver:dev
        container_name: prestohiveservercontainer
        ports:
            - 10000:10000
        volumes:
            - ./hivevol:/temporal
            - ./warehousevol:/user/hive/warehouse
            - ./metastorevol:/metastore
    postgresservice:
        image: postgres:10.6
        container_name: postgrescontainer
        volumes:
            - postgresdbvol:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: metastore
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres
    hiveclient:
        image: clientbuilder:dev
        container_name: clientbuildercontainer
        volumes:
            - ./client/project:/project
            - ./datavol:/data
        entrypoint:
            - bash
        tty: true
        stdin_open: true
volumes:
    postgresdbvol:


