select catalog_sales.*,
sold_date_dim.d_date_sk as sold_d_date_sk,
sold_date_dim.d_date_id as sold_d_date_id,
sold_date_dim.d_date as sold_d_date,
sold_date_dim.d_month_seq as sold_d_month_seq,
sold_date_dim.d_week_seq as sold_d_week_seq,
sold_date_dim.d_quarter_seq as sold_d_quarter_seq,
sold_date_dim.d_year as sold_d_year,
sold_date_dim.d_dow as sold_d_dow,
sold_date_dim.d_moy as sold_d_moy,
sold_date_dim.d_dom as sold_d_dom,
sold_date_dim.d_qoy as sold_d_qoy,
sold_date_dim.d_fy_year as sold_d_fy_year,
sold_date_dim.d_fy_quarter_seq as sold_d_fy_quarter_seq,
sold_date_dim.d_fy_week_seq as sold_d_fy_week_seq,
sold_date_dim.d_day_name as sold_d_day_name,
sold_date_dim.d_quarter_name as sold_d_quarter_name,
sold_date_dim.d_holiday as sold_d_holiday,
sold_date_dim.d_weekend as sold_d_weekend,
sold_date_dim.d_following_holiday as sold_d_following_holiday,
sold_date_dim.d_first_dom as sold_d_first_dom,
sold_date_dim.d_last_dom as sold_d_last_dom,
sold_date_dim.d_same_day_ly as sold_d_same_day_ly,
sold_date_dim.d_same_day_lq as sold_d_same_day_lq,
sold_date_dim.d_current_day as sold_d_current_day,
sold_date_dim.d_current_week as sold_d_current_week,
sold_date_dim.d_current_month as sold_d_current_month,
sold_date_dim.d_current_quarter as sold_d_current_quarter,
sold_date_dim.d_current_year as sold_d_current_year,
ship_date_dim.d_date_sk as ship_d_date_sk,
ship_date_dim.d_date_id as ship_d_date_id,
ship_date_dim.d_date as ship_d_date,
ship_date_dim.d_month_seq as ship_d_month_seq,
ship_date_dim.d_week_seq as ship_d_week_seq,
ship_date_dim.d_quarter_seq as ship_d_quarter_seq,
ship_date_dim.d_year as ship_d_year,
ship_date_dim.d_dow as ship_d_dow,
ship_date_dim.d_moy as ship_d_moy,
ship_date_dim.d_dom as ship_d_dom,
ship_date_dim.d_qoy as ship_d_qoy,
ship_date_dim.d_fy_year as ship_d_fy_year,
ship_date_dim.d_fy_quarter_seq as ship_d_fy_quarter_seq,
ship_date_dim.d_fy_week_seq as ship_d_fy_week_seq,
ship_date_dim.d_day_name as ship_d_day_name,
ship_date_dim.d_quarter_name as ship_d_quarter_name,
ship_date_dim.d_holiday as ship_d_holiday,
ship_date_dim.d_weekend as ship_d_weekend,
ship_date_dim.d_following_holiday as ship_d_following_holiday,
ship_date_dim.d_first_dom as ship_d_first_dom,
ship_date_dim.d_last_dom as ship_d_last_dom,
ship_date_dim.d_same_day_ly as ship_d_same_day_ly,
ship_date_dim.d_same_day_lq as ship_d_same_day_lq,
ship_date_dim.d_current_day as ship_d_current_day,
ship_date_dim.d_current_week as ship_d_current_week,
ship_date_dim.d_current_month as ship_d_current_month,
ship_date_dim.d_current_quarter as ship_d_current_quarter,
ship_date_dim.d_current_year as ship_d_current_year,
time_dim.*,
bill_customer.c_customer_sk as bill_c_customer_sk,
bill_customer.c_customer_id as bill_c_customer_id,
bill_customer.c_current_cdemo_sk as bill_c_current_cdemo_sk,
bill_customer.c_current_hdemo_sk as bill_c_current_hdemo_sk,
bill_customer.c_current_addr_sk as bill_c_current_addr_sk,
bill_customer.c_first_shipto_date_sk as bill_c_first_shipto_date_sk,
bill_customer.c_first_sales_date_sk as bill_c_first_sales_date_sk,
bill_customer.c_salutation as bill_c_salutation,
bill_customer.c_first_name as bill_c_first_name,
bill_customer.c_last_name as bill_c_last_name,
bill_customer.c_preferred_cust_flag as bill_c_preferred_cust_flag,
bill_customer.c_birth_day as bill_c_birth_day,
bill_customer.c_birth_month as bill_c_birth_month,
bill_customer.c_birth_year as bill_c_birth_year,
bill_customer.c_birth_country as bill_c_birth_country,
bill_customer.c_login as bill_c_login,
bill_customer.c_email_address as bill_c_email_address,
bill_customer.c_last_review_date as bill_c_last_review_date,
ship_customer.c_customer_sk as ship_c_customer_sk,
ship_customer.c_customer_id as ship_c_customer_id,
ship_customer.c_current_cdemo_sk as ship_c_current_cdemo_sk,
ship_customer.c_current_hdemo_sk as ship_c_current_hdemo_sk,
ship_customer.c_current_addr_sk as ship_c_current_addr_sk,
ship_customer.c_first_shipto_date_sk as ship_c_first_shipto_date_sk,
ship_customer.c_first_sales_date_sk as ship_c_first_sales_date_sk,
ship_customer.c_salutation as ship_c_salutation,
ship_customer.c_first_name as ship_c_first_name,
ship_customer.c_last_name as ship_c_last_name,
ship_customer.c_preferred_cust_flag as ship_c_preferred_cust_flag,
ship_customer.c_birth_day as ship_c_birth_day,
ship_customer.c_birth_month as ship_c_birth_month,
ship_customer.c_birth_year as ship_c_birth_year,
ship_customer.c_birth_country as ship_c_birth_country,
ship_customer.c_login as ship_c_login,
ship_customer.c_email_address as ship_c_email_address,
ship_customer.c_last_review_date as ship_c_last_review_date,
bill_cd.cd_demo_sk as bill_cd_demo_sk,
bill_cd.cd_gender as bill_cd_gender,
bill_cd.cd_marital_status as bill_cd_marital_status,
bill_cd.cd_education_status as bill_cd_education_status,
bill_cd.cd_purchase_estimate as bill_cd_purchase_estimate,
bill_cd.cd_credit_rating as bill_cd_credit_rating,
bill_cd.cd_dep_count as bill_cd_dep_count,
bill_cd.cd_dep_employed_count as bill_cd_dep_employed_count,
bill_cd.cd_dep_college_count as bill_cd_dep_college_count,
ship_cd.cd_demo_sk as ship_cd_demo_sk,
ship_cd.cd_gender as ship_cd_gender,
ship_cd.cd_marital_status as ship_cd_marital_status,
ship_cd.cd_education_status as ship_cd_education_status,
ship_cd.cd_purchase_estimate as ship_cd_purchase_estimate,
ship_cd.cd_credit_rating as ship_cd_credit_rating,
ship_cd.cd_dep_count as ship_cd_dep_count,
ship_cd.cd_dep_employed_count as ship_cd_dep_employed_count,
ship_cd.cd_dep_college_count as ship_cd_dep_college_count,
bill_hd.hd_demo_sk as bill_hd_demo_sk,
bill_hd.hd_income_band_sk as bill_hd_income_band_sk,
bill_hd.hd_buy_potential as bill_hd_buy_potential,
bill_hd.hd_dep_count as bill_hd_dep_count,
bill_hd.hd_vehicle_count as bill_hd_vehicle_count,
ship_hd.hd_demo_sk as ship_hd_demo_sk,
ship_hd.hd_income_band_sk as ship_hd_income_band_sk,
ship_hd.hd_buy_potential as ship_hd_buy_potential,
ship_hd.hd_dep_count as ship_hd_dep_count,
ship_hd.hd_vehicle_count as ship_hd_vehicle_count,
bill_ca.ca_address_sk as bill_ca_address_sk,
bill_ca.ca_address_id as bill_ca_address_id,
bill_ca.ca_street_number as bill_ca_street_number,
bill_ca.ca_street_name as bill_ca_street_name,
bill_ca.ca_street_type as bill_ca_street_type,
bill_ca.ca_suite_number as bill_ca_suite_number,
bill_ca.ca_city as bill_ca_city,
bill_ca.ca_county as bill_ca_county,
bill_ca.ca_state as bill_ca_state,
bill_ca.ca_zip as bill_ca_zip,
bill_ca.ca_country as bill_ca_country,
bill_ca.ca_gmt_offset as bill_ca_gmt_offset,
bill_ca.ca_location_type as bill_ca_location_type,
ship_ca.ca_address_sk as ship_ca_address_sk,
ship_ca.ca_address_id as ship_ca_address_id,
ship_ca.ca_street_number as ship_ca_street_number,
ship_ca.ca_street_name as ship_ca_street_name,
ship_ca.ca_street_type as ship_ca_street_type,
ship_ca.ca_suite_number as ship_ca_suite_number,
ship_ca.ca_city as ship_ca_city,
ship_ca.ca_county as ship_ca_county,
ship_ca.ca_state as ship_ca_state,
ship_ca.ca_zip as ship_ca_zip,
ship_ca.ca_country as ship_ca_country,
ship_ca.ca_gmt_offset as ship_ca_gmt_offset,
ship_ca.ca_location_type as ship_ca_location_type,
call_center.*, catalog_page.*, ship_mode.*, warehouse.*, promotion.*, item.*
from
catalog_sales, date_dim sold_date_dim, date_dim ship_date_dim, time_dim,
customer bill_customer, customer ship_customer, customer_demographics bill_cd, customer_demographics ship_cd,
household_demographics bill_hd, household_demographics ship_hd,
customer_address bill_ca, customer_address ship_ca, 
call_center, catalog_page, ship_mode, warehouse, promotion, item
where
cs_sold_date_sk = sold_date_dim.d_date_sk and
cs_sold_time_sk = t_time_sk and
cs_ship_date_sk = ship_date_dim.d_date_sk and
cs_bill_customer_sk = bill_customer.c_customer_sk and
cs_bill_cdemo_sk = bill_cd.cd_demo_sk and
cs_bill_hdemo_sk = bill_hd.hd_demo_sk and
cs_bill_addr_sk = bill_ca.ca_address_sk and
cs_ship_customer_sk = ship_customer.c_customer_sk and
cs_ship_cdemo_sk = ship_cd.cd_demo_sk and
cs_ship_hdemo_sk = ship_hd.hd_demo_sk and
cs_ship_addr_sk = ship_ca.ca_address_sk and
cs_call_center_sk = cc_call_center_sk and
cs_catalog_page_sk = cp_catalog_page_sk and
cs_ship_mode_sk = sm_ship_mode_sk and
cs_warehouse_sk = w_warehouse_sk and
cs_item_sk = i_item_sk and
cs_promo_sk = p_promo_sk
