version: '2.0'
services:
    hiveservice:
        image: hiveserverstandalone:dev
        container_name: namenodecontainer
        ports:
            - 4040:4040 #Spark driver GUI.
        volumes:
            - ./../vols/hive:/temporal
            - ./../vols/warehouse:/user/hive/warehouse
            - ./../vols/metastore:/home/${USER_NAME_DC}/metastore
            - ./../client/project:/project
            - ./../vols/data:/data
        environment:
            - USER_NAME_DC=${USER_NAME_DC}
            - RUN_HIVE_SERVER=0
    hiveclient:
        image: clientbuilder:dev
        container_name: clientbuildercontainer
        #volumes:
        #    - ./../client/project:/project
        #    - ./../vols/data:/data
        entrypoint:
            - bash
        tty: true
        stdin_open: true


